### ISSUE TITLE
pattern `InsecureRequestHttpsOnly` not covered

### ISSUE THREAD

**Issue by zy97** [qiniu/rust-sdk#10]
Sdk版本：qiniu-sdk = { version = "0.1.2" }
rustc版本：rustc 1.62.0 (a8314ef7d 2022-06-27)
编译不通过，编译日志：
Checking qiniu-ureq v0.1.2
error[E0004]: non-exhaustive patterns: `InsecureRequestHttpsOnly` not covered
   --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\qiniu-ureq-0.1.2\src\client.rs:255:37
    |
255 |     let response_error_kind = match kind {
    |                                     ^^^^ pattern `InsecureRequestHttpsOnly` not covered
    |
note: `ureq::ErrorKind` defined here
   --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ureq-2.5.0\src\error.rs:340:5        
    |
332 | / pub enum ErrorKind {
333 | |     /// The url could not be understood.
334 | |     InvalidUrl,
335 | |     /// The url scheme could not be understood.
...   |
340 | |     InsecureRequestHttpsOnly,
    | |     ^^^^^^^^^^^^^^^^^^^^^^^^ not covered
...   |
360 | |     HTTP,
361 | | }
    | |_-
    = note: the matched value is of type `ureq::ErrorKind`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
267 ~         UreqErrorKind::HTTP => ResponseErrorKind::InvalidRequestResponse,
268 ~         InsecureRequestHttpsOnly => todo!(),
    |

**Comment by bachue** [comment]
我们会尽快修复的

**Comment by bachue** [comment]
新的版本已经可以解决这个问题 https://github.com/qiniu/rust-sdk/releases/tag/v0.1.3
