### ISSUE TITLE
异步list查询

### ISSUE THREAD

**Issue by zy97** [qiniu/rust-sdk#19]
同步版本没有问题。
但异步版本请求如果没有任何满足条件的查询，它会一直请求，而且每次响应都不是一个正常结果
请求有结果的情况如下：
![image](https://user-images.githubusercontent.com/20431739/208044536-5e0943a8-6a66-406a-9697-3709e33966df.png)
----------------------------------------------------------------------
请求没有结果的情况如下：
![image](https://user-images.githubusercontent.com/20431739/208044694-757d2219-25a7-4980-939c-adf7edb5d255.png)
![image](https://user-images.githubusercontent.com/20431739/208044749-ff54a98d-11a7-49d1-b5f5-077e0a7b2b4c.png)
请问这是bug还是本来设计就是这样的

**Comment by bachue** [comment]
确实有 bug，会尽快修复的

**Comment by bachue** [comment]
fixed in https://github.com/qiniu/rust-sdk/pull/20#event-8083399409
