### ISSUE TITLE
关于上传成功后返回的hash字段

### ISSUE THREAD

**Issue by januwA** [qiniu/rust-sdk#7]
您好，我想问下上传是成功后返回的hash值是唯一的吗，比如这个
```json
{
        "h": "250",
        "hash": "FkZo1x3hf4IYwIseTf1pPYu2HMtq",
        "key": "image/6a5f01e4-cbfd-4c79-9779-4188c73e853b.jpg",
        "w": "202"
}
```

这个hash值是怎么计算的呢，我想保存这个hash值，减少重复上传相同文件

**Comment by bachue** [comment]
我们返回的是 `hash` 内的值是 etag，是根据我们自研的一种哈希算法得到的，可以判断文件内容是否一致，参考 https://developer.qiniu.com/kodo/1231/appendix 内的 Etag 算法一节。
